version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  api:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      REDI_URL: redis://redis:6379/0
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  worker:
    build: .
    restart: unless-stopped
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    command: celery -A app.core.celery_app worker --loglevel=info --concurrency=4

volumes:
  redis_data: